"""Graph-lasso Laplacian regime indicator research engine."""

from graph_regime.benchmarks import (
    compute_correlation_regime_score,
    compute_market_drawdown,
    compute_realized_volatility,
    create_stress_labels,
    load_fred_recession_indicator,
)
from graph_regime.component_overlays import (
    build_component_overlay_signals,
    compute_component_overlay_exposures,
    evaluate_component_overlays,
)
from graph_regime.component_scores import (
    GRAPH_COMPONENT_COLUMNS,
    add_component_scores,
    residualize_graph_components,
)
from graph_regime.data import (
    download_vix,
    download_yfinance_prices,
    load_prices_csv,
    load_returns_csv,
    prices_to_returns,
)
from graph_regime.evaluation import (
    align_indicator_and_benchmarks,
    classify_regimes_by_quantile,
    compute_contemporaneous_diagnostics,
    compute_event_study,
    compute_forward_targets,
    evaluate_predictive_power,
    summarize_regime_classes,
)
from graph_regime.features import compute_graph_features, compute_laplacian_spectrum
from graph_regime.graph_lasso import (
    GraphicalLassoFit,
    fit_graphical_lasso,
    fit_graphical_lasso_with_diagnostics,
    precision_to_partial_correlation,
)
from graph_regime.indicator import (
    GRAPH_LASSO_DIAGNOSTIC_COLUMNS,
    compute_regime_indicator,
    compute_rolling_graph_features,
    summarize_graph_lasso_convergence,
)
from graph_regime.laplacian import (
    adjacency_to_laplacian,
    partial_correlation_to_adjacency,
)
from graph_regime.phase6 import (
    DEFAULT_SAMPLE_SPLITS,
    Phase6Config,
    SampleSplits,
    apply_transaction_costs,
    assign_sample_period,
    build_phase6_tables_from_indicator,
    build_oos_outputs,
    compute_exposure_turnover,
    evaluate_transaction_cost_sensitivity,
    make_phase6_parameter_grid,
    make_phase6_quick_grid,
    run_incremental_information_tests,
    run_phase6_robustness_grid,
    select_oos_configuration,
)
from graph_regime.phase7 import (
    run_graph_component_ablation,
    run_model_ladder_incremental_tests,
)
from graph_regime.phase8 import (
    build_final_candidate_selection_matrix,
    build_phase8_candidate_scores,
    compare_information_sets,
    compute_algebraic_connectivity_diagnostics,
    compute_low_turnover_exposure,
    evaluate_algebraic_connectivity_overlays,
    evaluate_score_overlay_set,
    evaluate_turnover_reduction_overlays,
    make_rolling_origin_splits,
    rank_information_sets,
    run_rolling_origin_oos,
    select_low_turnover_candidate,
)
from graph_regime.pca_baselines import (
    PCA_FEATURE_COLUMNS,
    compute_rolling_pca_features,
)
from graph_regime.preprocessing import clean_returns, standardize_window
from graph_regime.risk_overlay import (
    apply_risk_overlay,
    compare_overlay_to_baseline,
    compute_benchmark_exposures,
    compute_exposure_from_indicator,
    compute_performance_metrics,
    compute_portfolio_returns,
    summarize_exposures,
)
from graph_regime.robustness import (
    compare_converged_vs_all_diagnostics,
    compute_benchmark_changes,
    compute_transition_correlations,
    create_stress_onset_labels,
    run_robustness_grid,
    summarize_robustness_diagnostics,
)

__all__ = [
    "adjacency_to_laplacian",
    "align_indicator_and_benchmarks",
    "apply_risk_overlay",
    "classify_regimes_by_quantile",
    "clean_returns",
    "compare_converged_vs_all_diagnostics",
    "compare_overlay_to_baseline",
    "compute_benchmark_changes",
    "compute_benchmark_exposures",
    "compute_contemporaneous_diagnostics",
    "compute_correlation_regime_score",
    "compute_event_study",
    "compute_exposure_from_indicator",
    "compute_forward_targets",
    "compute_graph_features",
    "compute_laplacian_spectrum",
    "compute_market_drawdown",
    "compute_performance_metrics",
    "compute_portfolio_returns",
    "compute_regime_indicator",
    "compute_realized_volatility",
    "compute_rolling_graph_features",
    "compute_exposure_turnover",
    "compute_transition_correlations",
    "create_stress_labels",
    "create_stress_onset_labels",
    "download_vix",
    "download_yfinance_prices",
    "evaluate_transaction_cost_sensitivity",
    "evaluate_predictive_power",
    "fit_graphical_lasso",
    "fit_graphical_lasso_with_diagnostics",
    "GRAPH_LASSO_DIAGNOSTIC_COLUMNS",
    "GraphicalLassoFit",
    "load_fred_recession_indicator",
    "load_prices_csv",
    "load_returns_csv",
    "make_phase6_parameter_grid",
    "make_phase6_quick_grid",
    "partial_correlation_to_adjacency",
    "precision_to_partial_correlation",
    "prices_to_returns",
    "run_robustness_grid",
    "run_incremental_information_tests",
    "run_phase6_robustness_grid",
    "select_oos_configuration",
    "standardize_window",
    "summarize_exposures",
    "summarize_regime_classes",
    "summarize_graph_lasso_convergence",
    "summarize_robustness_diagnostics",
    "apply_transaction_costs",
    "assign_sample_period",
    "build_oos_outputs",
    "build_final_candidate_selection_matrix",
    "build_phase8_candidate_scores",
    "build_phase6_tables_from_indicator",
    "build_component_overlay_signals",
    "compare_information_sets",
    "compute_component_overlay_exposures",
    "compute_algebraic_connectivity_diagnostics",
    "compute_low_turnover_exposure",
    "compute_rolling_pca_features",
    "evaluate_algebraic_connectivity_overlays",
    "evaluate_component_overlays",
    "evaluate_score_overlay_set",
    "evaluate_turnover_reduction_overlays",
    "GRAPH_COMPONENT_COLUMNS",
    "DEFAULT_SAMPLE_SPLITS",
    "make_rolling_origin_splits",
    "Phase6Config",
    "PCA_FEATURE_COLUMNS",
    "rank_information_sets",
    "SampleSplits",
    "add_component_scores",
    "residualize_graph_components",
    "run_graph_component_ablation",
    "run_model_ladder_incremental_tests",
    "run_rolling_origin_oos",
    "select_low_turnover_candidate",
]
